services:
  - type: web
    name: task-tracker
    env: ruby
    region: oregon
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-tracker-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test

databases:
  - name: task-tracker-db
    databaseName: task_tracker_production
    user: task_tracker
    region: oregon
    plan: starter